### ISSUE TITLE
tried the same approach as you did with Kustomize but didn't work

### ISSUE THREAD

**Issue by Newbie112222** [christianh814/kbe-apps#1]
Hi,
I followed the exact same strategy as mentioned in the document https://kubebyexample.com/learning-paths/argo-cd/argo-cd-working-kustomize.

this isn't working for me though since argoCD just spins around with status Unknown on the kustomization.yaml file. I dont see anything in the logs as well. Any ideas to troubleshoot this? I am trying to inject variables dynamically by using kustomize

**Comment by Newbie112222** [comment]
This is my implementation:
I am using argocd version v2.6.7. I am trying to utilize kustomize to replace a value in my deployment file by using patch.
Below is my implementation:

kustomization.yaml looks like below:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../test_deployment.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: testargo
    patch: |-
      - op: replace
        path: /spec/template/spec/containers
        value: us-west-2
```
I tried with having my deployment.yml in the same directory as the kustomization.yaml (seen below). In the code above i also tried with creating a copy of the kustomization file in a different folder and gave the neccessary path in my application.yml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - test_deployment.yaml
 ```
The issue here is that the kubectl kustomize . command is able to replace the value in my local but when deployed using argocd i see that the status is Unknown for the kustomization.yaml - it just keeps on spinning around and then fails. I am not seeing anything helpful in the logs as well.
